### ISSUE TITLE
Re-queueing page does not work 

### ISSUE THREAD

**Issue by lutejka** [harlan-zw/unlighthouse#126]
### Describe the bug

Trying to queue a route that was already scanned throws and error. After that, it wouldn't be scanned again. 

```ℹ Submitting / for a re-queue.                                   unlighthouse 5:26:27 PM
[h3] [unhandled] SystemError: Path is a directory: rm returned EISDIR (is a directory) /Users/lukas.matejka/.unlighthouse/google.com/8485/reports/__screenshot-thumbnails__
    at Object.rmSync (node:fs:1273:13)
    at file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/@unlighthouse/core/dist/index.mjs:5078:12
    at Array.forEach (<anonymous>)
    at Object.requeueReport (file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/@unlighthouse/core/dist/index.mjs:5077:36)
    at file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/@unlighthouse/core/dist/index.mjs:345:20
    at file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/@unrouted/core/dist/index.mjs:124:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/h3/dist/index.mjs:1255:19)
    at async Server.toNodeHandle (file:///Users/lukas.matejka/.nvm/versions/node/v18.15.0/lib/node_modules/unlighthouse/node_modules/h3/dist/index.mjs:1330:7) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined
}
```

### Reproduction

Scan a site, then try to rescann the route via UI

**Comment by harlan-zw** [comment]
Available in 0.8.7, thanks again for the help :)
