### ISSUE TITLE
Exception when using cookies

### ISSUE THREAD

**Issue by Kachoudas** [harlan-zw/unlighthouse#140]
### Describe the bug

When using the --cookies flag on the CLI there is an  exception in puppeteer-core:

```
√ Completed inspectHtmlTask for /. (1.23 KB took 0.6s)                                                                                                                                                                unlighthouse 16:10:01
file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:59
        _Callback_error.set(this, new ProtocolError());
                                  ^

ProtocolError: Protocol error (Network.deleteCookies): At least one of the url and domain needs to be specified
    at new Callback (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:59:35)
    at CallbackRegistry.create (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:104:26)
    at Connection._rawSend (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:219:26)
    at CDPSessionImpl.send (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:426:78)
    at CDPPage.deleteCookie (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:349:70)
    at CDPPage.setCookie (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:364:20)
    at runLighthouseTask (file:///C:/Users/Username/AppData/Local/npm-cache/_npx/944abecbf21dfffb/node_modules/@unlighthouse/core/dist/index.mjs:4889:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

### Reproduction

npx unlighthouse --site example.net --cookies "testCookie=1" -d

### System / Nuxt Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 16.82 GB / 31.89 GB
Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.19041.1566
```

**Comment by harlan-zw** [comment]
Thanks! This should be fixed in 0.10.0
