### ISSUE TITLE
Error: "The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable"

### ISSUE THREAD

**Issue by bluepuma77** [harlan-zw/unlighthouse#247]
### Describe the bug

It sounds really easy according to doc to get up and running with:
```
npx unlighthouse --site <your-site>
```
But on a bare Debian server install it will only show error:
```
# npx unlighthouse --site example.com
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

ChromePathNotSetError
    at new LauncherError (file:///root/node_modules/chrome-launcher/dist/utils.js:22:22)
    at new ChromePathNotSetError (file:///root/node_modules/chrome-launcher/dist/utils.js:28:9)
    at Module.linux (file:///root/node_modules/chrome-launcher/dist/chrome-finder.js:124:15)
    at Launcher.getFirstInstallation (file:///root/node_modules/chrome-launcher/dist/chrome-launcher.js:122:43)
    at resolveUserConfig (file:///root/node_modules/@unlighthouse/core/dist/index.mjs:1749:33)
    at async createUnlighthouse (file:///root/node_modules/@unlighthouse/core/dist/index.mjs:1891:26)
    at async run (file:///root/node_modules/@unlighthouse/cli/dist/cli.mjs:19:24) {
  message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
  code: 'ERR_LAUNCHER_PATH_NOT_SET'
}

Node.js v22.10.0
```

It would be great to have a simple paragraph or FAQ item what else to install and set on Linux.

### Reproduction

Run `npx unlighthouse --site <your-site>` on bare Debian server install

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 2.92 GB / 3.73 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 22.10.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
```

**Comment by harlan-zw** [comment]
Thanks for the issue, I didn't realise this code would throw when no paths were found. It should now correctly fallback to downloading a chrome binary to run the scan.
