### ISSUE TITLE
[yarn] - Missing dependency radix3

### ISSUE THREAD

**Issue by wh1t3h47** [harlan-zw/unlighthouse#254]
### Describe the bug

when invoked using yarn dlx with yarn version berry

```
yarn dlx unlighthouse --site  pellizzetti.adv.br
➤ YN0000: · Yarn 4.4.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + unlighthouse@npm:0.14.1, @ampproject/remapping@npm:2.3.0, @antfu/utils@npm:0.7.10, and 553 more.
➤ YN0000: └ Completed in 6s 138ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide puppeteer (pf45d9), requested by unlighthouse.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 520 packages were added to the project (+ 220.1 MiB).
➤ YN0000: └ Completed in 3s 932ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @parcel/watcher@npm:2.5.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.23.1 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 165ms
➤ YN0000: · Done with warnings in 11s 367ms


node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: @unlighthouse/core tried to access radix3, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: radix3 (via "radix3/package.json")
Required by: @unlighthouse/core@virtual:d951aaedb7f942da600c8791d579762191521344518b51241cf2dfa4f25fb69007c72ef6b41e8f8fa49c1b7e2266553e07bfd0809f2349cd243d2e8f7dd5680a#npm:0.14.1 (via /tmp/xfs-77757043/dlx-39653/.yarn/__virtual__/@unlighthouse-core-virtual-3995a212e3/0/cache/@unlighthouse-core-npm-0.14.1-28a9adbe44-e66117aa58.zip/node_modules/@unlighthouse/core/dist/index.mjs)

    at makeError (/tmp/xfs-77757043/dlx-39653/.pnp.cjs:11471:34)
    at resolveToUnqualified (/tmp/xfs-77757043/dlx-39653/.pnp.cjs:13109:21)
    at Object.resolveToUnqualified (/tmp/xfs-77757043/dlx-39653/.pnp.cjs:13289:26)
    at resolve$1 (file:///tmp/xfs-77757043/dlx-39653/.pnp.loader.mjs:2031:31)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:278:30)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.9.0
```

### Reproduction

yarn dlx unlighthouse --site  pellizzetti.adv.br

### System / Nuxt Info

```Shell
Node.js v20.9.0
Yarn 4.4.1
Linux debian 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-05-17) x86_64 GNU/Linux
```

**Comment by harlan-zw** [comment]
Thanks, not too sure why the build pipeline didn't flag this but I've pushed up a fix.
