### ISSUE TITLE
Axios bump to 1.2.1  Throws an error : "FATAL  Request to site https://example.com threw an unhandled exception. Please check the URL is valid. unexpected end of file" on some sites

### ISSUE THREAD

**Issue by MamlukiSn** [harlan-zw/unlighthouse#42]
### Describe the bug

The latest 0.4.4 release throw an error on some valid sites (not all).

```
› Testing Site https://www.example.com/ is valid.                                                                                    unlighthouse 15:36:01

  at Function.AxiosError.from (node_modules/unlighthouse/node_modules/axios/lib/core/AxiosError.js:89:14)
  at BrotliDecompress.handleStreamError (node_modules/unlighthouse/node_modules/axios/lib/adapters/http.js:489:29)
  at BrotliDecompress.emit (events.js:412:35)
  at emitErrorNT (internal/streams/destroy.js:106:8)
  at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)

 FATAL  Request to site https://www.example.com/ threw an unhandled exception. Please check the URL is valid. unexpected end of file
```
This is related to bumping the axios dependency for the core `"axios": "^1.1.3"`, which defaults to the latest `v1.2.1.` The error has also been documented here [https://github.com/axios/axios/issues/5346](https://github.com/axios/axios/issues/5346).

Adding encoding headers to the function as suggested in[https://github.com/axios/axios/issues/5346#issuecomment-1340241163]( https://github.com/axios/axios/issues/5346#issuecomment-1340241163 ) fixes this. I think also downgrading to axios 1.1.3 as suggested on the thread would fix it.

```
async function fetchUrlRaw(url) {
  try {
    const response = await axios.get(url, {
      headers: { "Accept-Encoding": "gzip,deflate,compress" },
      httpsAgent: new https.Agent({
        rejectUnauthorized: false
      })
    });
    const redirected = response.request.res.responseUrl && response.request.res.responseUrl !== url;
    const redirectUrl = response.request.res.responseUrl;
    if (response.status < 200 || response.status >= 300 && !redirected) {
      return {
        valid: false,
        redirected,
        response,
        redirectUrl
      };
    }
    return {
      valid: true,
      redirected,
      response,
      redirectUrl
    };
  } catch (e) {
    return {
      error: e,
      valid: false
    };
  }
}
```

Version 0.4.2 and below are working fine.

### System Info

```Shell
System:
  OS: macOS 12.2.1
  CPU: (10) x64 Apple M1 Pro
  Memory: 230.56 MB / 32.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 14.17.6 - ~/.asdf/installs/nodejs/14.17.6/bin/node
  npm: 6.14.15 - ~/.asdf/plugins/nodejs/shims/npm
Browsers:
  Chrome: 108.0.5359.124
  Safari: 15.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thomasbnt** [comment]
Hello, 
same issue for me.

```bash
Node v18.9.0
NPM v8.19.2
```

```bash
thomasbnt@homelab:~/lab$ npx unlighthouse --site https://thomasbnt.dev/en/

 FATAL  Request to site https://thomasbnt.dev/en/ threw an unhandled exception. Please check the URL is valid. unexpected end of file

  at AxiosError.from (/home/thomasbnt/.npm/_npx/944abecbf21dfffb/node_modules/axios/lib/core/AxiosError.js:89:14)
  at BrotliDecompress.handleStreamError (/home/thomasbnt/.npm/_npx/944abecbf21dfffb/node_modules/axios/lib/adapters/http.js:489:29)
  at BrotliDecompress.emit (node:events:525:35)
  at emitErrorNT (node:internal/streams/destroy:151:8)
  at emitErrorCloseNT (node:internal/streams/destroy:116:3)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by harlan-zw** [comment]
Hey @MamlukiSn 

Thanks for the issue and the research behind it. Have pushed up a fix, just going to lock axios, for now, to make life easier.

**Comment by MamlukiSn** [comment]
Thanks for the update @harlan-zw .
