### ISSUE TITLE
Gitlab CI run fails with possible missing flag

### ISSUE THREAD

**Issue by pennal** [harlan-zw/unlighthouse#49]
### Describe the bug

I am running unlighthouse on Gitlab CI and I am running into the following issue:

```
$ unlighthouse-ci --site mysite.org --build-static
[success] [unlighthouse] Successfully connected to `mysite.org`, status code: `200`.
[warn] [unlighthouse] Warn: No CI budget has been set. Consider setting a budget with the config (`ci.budget`) or --budget <number>.
[info] [unlighthouse] Discovered 32 routes from sitemap.xml.
/usr/local/lib/node_modules/@unlighthouse/cli/node_modules/puppeteer-cluster/dist/Cluster.js:146
                throw new Error(`Unable to launch browser for worker, error message: ${err.message}`);
                      ^
Error: Unable to launch browser for worker, error message: Failed to launch the browser process!
[0324/151509.041470:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at Cluster.<anonymous> (/usr/local/lib/node_modules/@unlighthouse/cli/node_modules/puppeteer-cluster/dist/Cluster.js:146:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@unlighthouse/cli/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I am using a custom image based on the `node` image, which uses Debian. The image is produced using the following file:

```
ARG NODE_IMAGE_TAG=$NODE_IMAGE_TAG

FROM node:$NODE_IMAGE_TAG

# Install pnpm
RUN npm install -g pnpm

RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
#    libgtk-4-1 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1 \
    wget

# Install chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install ./google-chrome-stable_current_amd64.deb

# Install unlighthouse
RUN npm install -g  @unlighthouse/cli puppeteer
```

From what I understand, the puppeteer browser launcher may need additional flags:

```
puppetter.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})
```

I believe this may be solved by adding a flag (`--no-sandbox`) to the unlighthouse CLI, so as to choose when to run it this way

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.29.3`
- Builder:          `vite`
- User Config:      `experimental`, `runtimeConfig`, `hooks`, `build`, `modules`, `tailwindcss`, `vite`, `sitemap`, `image`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.7`, `@nuxtjs/tailwindcss@6.6.4`, `@funken-studio/sitemap-nuxt-3@4.0.4`, `@nuxtjs/plausible@0.2.0`, `@nuxt/image-edge@1.0.0-27968280.9739e4d`
- Build Modules:    `-`
```

**Comment by pennal** [comment]
After a bit of digging, I have found a way to configure this in puppeteer using the [BrowserLaunchArgumentOptions](https://pptr.dev/api/puppeteer.browserlaunchargumentoptions) interface. 

You can configure multiple flags in the config file `unlighthouse.config.ts` using the `puppeteerOptions` key:

```ts
export default {
  // Other settings
  puppeteerOptions: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
};
```

This now runs fine on Gitlab CI! It would be nice to add this as an example in the docs

**Comment by harlan-zw** [comment]
Thank you @pennal, this is now documented on the [Docker](https://unlighthouse.dev/guide/guides/docker) docs page.
