### ISSUE TITLE
ERR_INVALID_ARG_TYPE error while trying single run

### ISSUE THREAD

**Issue by bux** [harlan-zw/unlighthouse#5]
OS: Windows 10
node js: v16.13.2

I'm getting the following error when trying `pnpm dlx unlighthouse --site https://unlighthouse.dev/guide/`

```
√ Successfully connected to https://unlighthouse.dev/guide/, status code: 200.                                                                unlighthouse 15:51:16
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (node:fs:393:10)
    at go$readFile (C:\Users\jo\AppData\Local\Temp\dlx-7572\5\node_modules\.pnpm\graceful-fs@4.2.9\node_modules\graceful-fs\graceful-fs.js:118:14)
    at Object.readFile (C:\Users\jo\AppData\Local\Temp\dlx-7572\5\node_modules\.pnpm\graceful-fs@4.2.9\node_modules\graceful-fs\graceful-fs.js:115:12)
    at C:\Users\jo\AppData\Local\Temp\dlx-7572\5\node_modules\.pnpm\universalify@2.0.0\node_modules\universalify\index.js:8:12
    at new Promise (<anonymous>)
    at Object.readFile (C:\Users\jo\AppData\Local\Temp\dlx-7572\5\node_modules\.pnpm\universalify@2.0.0\node_modules\universalify\index.js:7:14)
    at generateClient (file:///C:/Users/jo/AppData/Local/Temp/dlx-7572/5/node_modules/.pnpm/@unlighthouse+core@0.2.0/node_modules/@unlighthouse/core/dist/index.mjs:906:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.ctx.setServerContext (file:///C:/Users/jo/AppData/Local/Temp/dlx-7572/5/node_modules/.pnpm/@unlighthouse+core@0.2.0/node_modules/@unlighthouse/core/dist/index.mjs:1228:5)
    at async run (file:///C:/Users/jo/AppData/Local/Temp/dlx-7572/5/node_modules/.pnpm/@unlighthouse+cli@0.2.0/node_modules/@unlighthouse/cli/dist/cli.mjs:27:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
 ERROR  Command failed with exit code 1: C:\Users\jo\AppData\Local\Temp\dlx-7572\unlighthouse.CMD --site https://unlighthouse.dev/guide/
```

**Comment by thomasbnt** [comment]
Same error with 

`npx unlighthouse --site unlighthouse.dev --debug`

**Comment by harlan-zw** [comment]
Hey @bux & @thomasbnt 

Thanks for reporting this issue. Looks like it was a bug with Windows.

I've pushed up a fix and it seems to be working. 

Would you mind trying again with the command

```
pnpm dlx unlighthouse@latest --site https://unlighthouse.dev
```

or 

```
npx unlighthouse@latest --site unlighthouse.dev --debug
```

**Comment by bux** [comment]
@harlan-zw Yeah, that looks good. Thank you for the fast fix :)

**Comment by not-nemlig** [comment]
I just got the same issue today, trying it out. I run on a mac.

```➜  ~ npx unlighthouse@latest --site nemlig.com --debug
› Starting Unlighthouse at root: /Users/nickiskipper cwd: /Users/nickiskipper                                                                            unlighthouse 07:00:44
› Discovered config definition {                                                                                                                         unlighthouse 07:00:44
  config: undefined,
  sources: []
}
› Unable to locale page files, disabling route discovery.                                                                                                unlighthouse 07:00:44
› Found chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome.                                                                          unlighthouse 07:00:44
› Post config resolution {                                                                                                                               unlighthouse 07:00:44
  routerPrefix: '/',
  apiPrefix: '/api',
  cache: true,
  client: {
    groupRoutesKey: 'route.definition.name',
    columns: {
      overview: [Array],
      performance: [Array],
      accessibility: [Array],
      'best-practices': [Array],
      seo: [Array]
    }
  },
  scanner: {
    customSampling: {},
    ignoreI18nPages: true,
    maxRoutes: 200,
    skipJavascript: true,
    samples: 1,
    throttle: false,
    crawler: true,
    dynamicSampling: 5,
    sitemap: true,
    device: 'mobile'
  },
  server: {
    port: 5678,
    showURL: false,
    open: true
  },
  discovery: false,
  root: '/Users/nickiskipper',
  outputPath: '.unlighthouse',
  debug: true,
  puppeteerOptions: {
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    defaultViewport: {
      width: 360,
      height: 640
    }
  },
  puppeteerClusterOptions: {
    monitor: true,
    workerCreationDelay: 500,
    retryLimit: 3,
    timeout: 300000,
    maxConcurrency: 8,
    skipDuplicateUrls: false,
    retryDelay: 2000,
    concurrency: 3,
    puppeteer: PuppeteerNode {
      _changedProduct: false,
      _isPuppeteerCore: true,
      connect: [Function: bound bound connect],
      configuration: [Object],
      defaultBrowserRevision: '1108766',
      launch: [Function: bound launch],
      executablePath: [Function: bound executablePath],
      defaultArgs: [Function: bound defaultArgs],
      createBrowserFetcher: [Function: bound createBrowserFetcher]
    }
  },
  lighthouseOptions: {
    onlyCategories: [
      'performance',
      'accessibility',
      'best-practices',
      'seo'
    ],
    throttlingMethod: 'provided',
    throttling: {
      rttMs: 0,
      throughputKbps: 0,
      cpuSlowdownMultiplier: 1,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0
    },
    formFactor: 'mobile',
    screenEmulation: {
      mobile: true,
      width: 360,
      height: 640,
      deviceScaleFactor: 2
    }
  },
  urls: [],
  site: 'https://nemlig.com/',
  hooks: {
    'resolved-config': [AsyncFunction: resolved-config]
  }
}
› Testing Site https://nemlig.com/ is valid.                                                                                                             unlighthouse 07:00:44
✔ Request to site https://nemlig.com/ redirected to https://www.nemlig.com/, using that as the site.                                                     unlighthouse 07:00:45
› Creating Unlighthouse                                                                                                                                  unlighthouse 07:00:45
› Setting Unlighthouse Site URL [Site: https://www.nemlig.com/]                                                                                          unlighthouse 07:00:45
› Setting Unlighthouse Server Context [Server: http://localhost:5678/]                                                                                   unlighthouse 07:00:45
› Creating new Unrouted ctx: unlighthouse-api {                                                                                                      unlighthouse-api 07:00:45
  debug: true,
  prefix: '/',
  middleware: [],
  hooks: {
    'serve:before-route': [Function: serve:before-route]
  },
  plugins: [
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    }
  ],
  presets: [
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    },
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    }
  ],
  name: 'unlighthouse-api',
  app: {
    use: [Function: use],
    handler: [AsyncFunction (anonymous)] {
      __is_handler__: true
    },
    stack: [],
    options: {}
  }
}
› Using preset: @unrouted/preset-api@0.5.0                                                                                                           unlighthouse-api 07:00:45
› Using preset: @unrouted/preset-node@0.5.0                                                                                                          unlighthouse-api 07:00:45
› Using plugin: lazyRouteHandles                                                                                                                     unlighthouse-api 07:00:45
› Registering route get /__lighthouse.                                                                                                               unlighthouse-api 07:00:45
› Registering route post /api/reports/rescan.                                                                                                        unlighthouse-api 07:00:45
› Registering route post /api/reports/:id/rescan.                                                                                                    unlighthouse-api 07:00:45
› Registering route get,head /api/__launch.                                                                                                          unlighthouse-api 07:00:45
› Registering route get,head /api/ws.                                                                                                                unlighthouse-api 07:00:45
› Registering route get,head /api/reports.                                                                                                           unlighthouse-api 07:00:45
› Registering route get,head /api/scan-meta.                                                                                                         unlighthouse-api 07:00:45
› Registering route get /**.                                                                                                                         unlighthouse-api 07:00:45
› Registering route get /.                                                                                                                           unlighthouse-api 07:00:45
› Setting up 9 routes.                                                                                                                               unlighthouse-api 07:00:45
› Starting Unlighthouse [Server: http://localhost:5678/ Site: https://www.nemlig.com/ Debug: true]                                                       unlighthouse 07:00:45
› Attempting to fetch sitemap at https://www.nemlig.com/sitemap.xml                                                                                      unlighthouse 07:00:45
Error occurred during "crawl('https://www.nemlig.com/sitemap.xml')":
 Error: HTTP Error occurred: Response code 404 (Not Found)
› Fetched sitemap with 0 URLs.                                                                                                                           unlighthouse 07:00:45
ℹ Sitemap appears to be missing, falling back to crawler mode.                                                                                           unlighthouse 07:00:45
› Route has been queued. Path: / Name: _index.                                                                                                           unlighthouse 07:00:45

   ╭─────────────────────────────────────────╮
   │                                         │
   │   ⛵  unlighthouse cli @ v0.5.1         │
   │                                         │
   │   ▸ Scanning: https://www.nemlig.com/   │
   │   ▸ Route Discovery: Crawler            │
   │                                         │
   │   Root: /Users/nickiskipper             │
   │   URL: http://localhost:5678/           │
   │                                         │
   ╰─────────────────────────────────────────╯


  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

› GET /favicon.ico 200 undefined - 0ms                                                                                                               unlighthouse-api 07:00:46
› GET /api/scan-meta 200 object - 0ms                                                                                                                unlighthouse-api 07:00:46
› GET /api/reports 200 object - 1ms                                                                                                                  unlighthouse-api 07:00:46
› HTML extract of https://www.nemlig.com/ took 918ms                                                                                                     unlighthouse 07:00:47
› Route has been queued. Path: / Name: _index.                                                                                                           unlighthouse 07:00:47
ℹ No internal links discovered on home page. Switching crawler to execute javascript.                                                                    unlighthouse 07:00:47
✔ Completed inspectHtmlTask for /. [Size: NaN undefined]                                                                                                 unlighthouse 07:00:47

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at Object.writeFileSync (node:fs:2239:5)
    at inspectHtmlTask (file:///Users/nickiskipper/.npm/_npx/9dcacbe7dba6f79c/node_modules/@unlighthouse/core/dist/index.mjs:645:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.15.0```

**Comment by mzaien** [comment]
> ```
> pnpm dlx unlighthouse@latest --site https://unlighthouse.dev
> ```

Same here, I tired node 16/18/20 , npx/pnpx and nothing works

**Comment by camcnz** [comment]
This [line](https://github.com/harlan-zw/unlighthouse/blob/fb2fe2b2a6a931d8385b6cfd3d243d844125a30d/packages/core/src/puppeteer/tasks/html.ts#L174) is failing and needs a try catch around it.
